
@AUTH_TOKEN = Bearer xxxxxxx.xxxx

# Use http:// if testing with heroku:local (Redis Issue)
@BASE_URL = https://127.0.0.1:5000
# @BASE_URL = http://127.0.0.1:5000

GET {{BASE_URL}}
###
GET {{BASE_URL}}/throw
###
GET {{BASE_URL}}/error
###
GET {{BASE_URL}}/async
###
POST {{BASE_URL}}/login
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "supersecret1"
}

###
GET {{BASE_URL}}/redis/testKey
###

GET {{BASE_URL}}/team/tenants
###
POST {{BASE_URL}}/team/tenants
Content-Type: application/json

{
  "name": "Test Tenant 5",
  "dbName": "t-tenant5"
}
###
DELETE {{BASE_URL}}/team/tenants/t-tenant4
###