name: CI/CD

on:
  push:
    branches:
      - "main"
      - "staging"
  pull_request:
    branches:
      - "main"
      - "staging"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install dependencies
      run: |
        npm ci
    - name: run lint check
      run: |
        npm run lint:check
    # - name: run tests
      # run: |
        # npm test
    - name: run build
      run: |
        npm run build --if-present
